COMPONENT=src/SoftwareEnergyOverflowTestC

CFLAGS += -Isrc

CFLAGS += -DSOFTWAREENERGY
CFLAGS += -I$(TOSDIR)/lib/softwareenergy

BUILD_EXTRA_DEPS += 
CLEAN_EXTRA = simbuild build doc app.xml 

include $(MAKERULES)