#!/bin/bash

###### CONFIG START ######
LPL=512
PERIOD=2048
ENERGY=200
FOLDER=2b_smallramp1to128_lpl${LPL}_delay10_period${PERIOD}_init9_battery$ENERGY

let MAX_ENERGY=$ENERGY*65768

##### MAKE DIRECTORY #####

if [ -d matlab/$FOLDER ]
then 
    echo "WARNING: Directory already exists, you might be overriding some files"
    echo "Sure you want to continue? [y|n]"
    read line
    if [ "$line" != "y" ]
        then
        echo "Exiting..."
        exit
    fi
else
    mkdir matlab/$FOLDER
fi


##### RUN TESTS #####

#for ((t=10; t<=1; t=t+1))
for ((t=-1; t<=5; t=t+1))
do
v=-1
if [ "$t" -eq "$v" ]
then
threshold=VAR
env CFLAGS="-DDEFAULT_SAMPLE_INTERVAL=${PERIOD} -DLPL_DEF_LOCAL_WAKEUP=${LPL} -DLPL_DEF_REMOTE_WAKEUP=${LPL}" make micaz sim-sf tinydebug
else
let threshold=2**${t}
env CFLAGS="-DDEFAULT_SAMPLE_INTERVAL=${PERIOD} -DLPL_DEF_LOCAL_WAKEUP=${LPL} -DLPL_DEF_REMOTE_WAKEUP=${LPL} -DSELECTIVE_FIXED_THRESHOLD=${threshold}" make micaz sim-sf tinydebug
fi

echo $threshold

#TODO: run this config and compare results to paper results 

#for ((run=10; run<=1; run=run+1))
for ((run=1; run<=5; run=run+1))
do

java net.tinyos.tools.DebugClient -comm sf@localhost:9002 > matlab/$FOLDER/threshold${threshold}_run${run}.log &
#python sim.py | grep --line-buffered "Energy used" | sed --unbuffered 's/[^:]*[^0-9]*\([0-9]*\)/\1/' | {

python sim.py | sed --unbuffered -n 's/.*Energy used \([0-9]*\)/\1/p' | {

while read line
do
    echo "line is $line"
    echo "max is $MAX_ENERGY"
    if [ $line -ge $MAX_ENERGY ]
    then
        echo "KILL"
        pkill python
        break
    else
        echo "KEEP"
    fi
done

}

# Give SF and DebugClient time to write all data to file
sleep 2

pkill java

done

done

##### PROCESS LOGS #####

matlab -nosplash -nodisplay -r "debug2mat('matlab/${FOLDER}');exit;"
